//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstitutoServices.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstitutoServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AIzaSyBmHgrN0BoHgd0ZlDqY9f_BygkzOfhuP_E.
        /// </summary>
        public static string ApiKeyFirebase {
            get {
                return ResourceManager.GetString("ApiKeyFirebase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AIzaSyDLPkmzvqIWwmhKQkNapfWd-x-_0WCvudk.
        /// </summary>
        public static string ApiKeyGoogleCloud {
            get {
                return ResourceManager.GetString("ApiKeyGoogleCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a instituto20-435114.firebaseapp.com.
        /// </summary>
        public static string AuthDomainFirebase {
            get {
                return ResourceManager.GetString("AuthDomainFirebase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 243005933117-9jrpnqa9f296itha7jlaa3nmh23et4vu.
        /// </summary>
        public static string client_id {
            get {
                return ResourceManager.GetString("client_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logoISP20 {
            get {
                object obj = ResourceManager.GetObject("logoISP20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a false.
        /// </summary>
        public static string Remoto {
            get {
                return ResourceManager.GetString("Remoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost:7202/api/.
        /// </summary>
        public static string UrlApiLocal {
            get {
                return ResourceManager.GetString("UrlApiLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://datainstituto.azurewebsites.net/api/.
        /// </summary>
        public static string UrlApiRemoto {
            get {
                return ResourceManager.GetString("UrlApiRemoto", resourceCulture);
            }
        }
    }
}
