services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - app_network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    networks:
      - app_network

  backend:
    image: aleramirezsj/instituto-backend:latest
    build:
      context: .
      dockerfile: DockerfileBack
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80
      - VIRTUAL_HOST=api.isp20.edu.ar
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=api.isp20.edu.ar
      - LETSENCRYPT_EMAIL=aleramirezsj@gmail.com
      - IS_CONTAINER=true
    networks:
      - app_network
    depends_on:
      - nginx-proxy

  frontend:
    image: aleramirezsj/instituto-frontend:latest
    build:
      context: .
      dockerfile: DockerfileWeb
    restart: always
    environment:
      - VIRTUAL_PROTO=https # ✅ Asegura que el proxy inverso use HTTPS
      - VIRTUAL_HOST=app.isp20.edu.ar
      - LETSENCRYPT_HOST=app.isp20.edu.ar
      - LETSENCRYPT_EMAIL=aleramirezsj@gmail.com
    networks:
      - app_network
    depends_on:
      - nginx-proxy
      - backend

networks:
  app_network:
    driver: bridge

volumes:
  certs:
  html:
  vhost:
  acme: